using Microsoft.Extensions.Logging;

namespace Our.Umbraco.CookieConsent.Configuration;

public class CookieConsentOptions
{
    public const string SectionName = "Umbraco:CookieConsent";

    // Opt-out for sites where a deployment tool (Umbraco Deploy/uSync) transfers the dictionary keys
    public bool DoNotAutoGenerateDictionaryItems { get; set; }

    // Level used for the per-key seeding logs
    public LogLevel SeedLogLevel { get; set; } = LogLevel.Debug;
}
