using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Our.Umbraco.CookieConsent.Configuration;
using Our.Umbraco.CookieConsent.Models;
using Our.Umbraco.CookieConsent.Services;
using Umbraco.Cms.Core;
using Umbraco.Cms.Core.Models;
using Umbraco.Cms.Core.Services;

namespace Our.Umbraco.CookieConsent;

public class DictionaryKeySeeder
{
    private readonly IDictionaryItemService _dictionaryItemService;
    private readonly ILanguageService _languageService;
    private readonly ILogger<CookieConsentService> _logger;
    private readonly IOptions<CookieConsentOptions> _options;

    public DictionaryKeySeeder(IDictionaryItemService dictionaryItemService,
        ILanguageService languageService,
        ILogger<CookieConsentService> logger,
        IOptions<CookieConsentOptions> options)
    {
        _dictionaryItemService = dictionaryItemService;
        _languageService = languageService;
        _logger = logger;
        _options = options;
    }

    private bool AutoGenerateDisabled => _options.Value.DoNotAutoGenerateDictionaryItems;

    private LogLevel SeedLogLevel => _options.Value.SeedLogLevel;

    public async Task CreateBaseKeysAsync()
    {
        if (AutoGenerateDisabled)
        {
            _logger.LogInformation("Skipping dictionary key seeding (DoNotAutoGenerateDictionaryItems is true)");
            return;
        }

        var parentKey = await CreateKeyAsync(Translations.NAMESPACE, "-");
        await CreateKeyAsync(Translations.ConsentModal.Title, "Your Privacy Settings", parentKey);
        await CreateKeyAsync(Translations.ConsentModal.Description, "We use cookies to improve your experience, analyze traffic, and personalize content. You can manage your preferences below or accept all cookies.", parentKey);
        await CreateKeyAsync(Translations.ConsentModal.CloseIconLabel, "Close this dialog", parentKey);
        await CreateKeyAsync(Translations.ConsentModal.AcceptAll, "Accept All Cookies", parentKey);
        await CreateKeyAsync(Translations.ConsentModal.RejectAll, "Reject All Cookies", parentKey);
        await CreateKeyAsync(Translations.ConsentModal.ManagePreferences, "Manage Cookie Preferences", parentKey);
        await CreateKeyAsync(Translations.ConsentModal.Footer, "Your choices will be saved for future visits. You can update them at any time.", parentKey);

        await CreateKeyAsync(Translations.PreferencesModal.Title, "Manage Your Cookie Preferences", parentKey);
        await CreateKeyAsync(Translations.PreferencesModal.CloseIconLabel, "Close preferences dialog", parentKey);
        await CreateKeyAsync(Translations.PreferencesModal.AcceptAll, "Accept All Cookies", parentKey);
        await CreateKeyAsync(Translations.PreferencesModal.RejectAll, "Reject All Cookies", parentKey);
        await CreateKeyAsync(Translations.PreferencesModal.Save, "Save My Preferences", parentKey);
        // orestbida prefixes the count and picks singular/plural split on '|'
        await CreateKeyAsync(Translations.PreferencesModal.ServiceCounterLabel, "Enabled service|Enabled services", parentKey);
    }

    // sectionName = analytics / marketing / functional ...
    public async Task CreateSectionAsync(string sectionName)
    {
        if (AutoGenerateDisabled)
        {
            _logger.LogInformation("Skipping dictionary section seeding for {Section} (DoNotAutoGenerateDictionaryItems is true)", sectionName);
            return;
        }

        var parentKey = (await _dictionaryItemService.GetAsync(Translations.NAMESPACE))?.Key
                        ?? await CreateKeyAsync(Translations.NAMESPACE, "-");

        parentKey = await CreateKeyAsync(sectionName, "-", parentKey);

        string title;
        string description;

        switch (sectionName.ToLower())
        {
            case "analytics":
                title = "Analytics Preferences";
                description = "These cookies help us understand how visitors interact with the website by collecting and reporting information anonymously.";
                break;

            case "marketing":
                title = "Marketing Preferences";
                description = "These cookies are used to deliver advertisements more relevant to you and your interests.";
                break;

            case "functionality":
                title = "Functional Preferences";
                description = "These cookies enable the website to provide enhanced functionality and personalization.";
                break;

            case "necessary":
                title = "Essential Preferences";
                description = "These cookies are necessary for the website to function and cannot be switched off in our systems.";
                break;

            default:
                title = "Other Preferences";
                description = "These cookies support additional functionalities or services.";
                break;
        }

        await CreateKeyAsync(string.Format(Translations.PreferencesModal.Sections.Title, sectionName), title, parentKey);
        await CreateKeyAsync(string.Format(Translations.PreferencesModal.Sections.Description, sectionName), description, parentKey);
    }

    private async Task<Guid?> CreateKeyAsync(string key, string value, Guid? parentKey = null)
    {
        try
        {
            var itemId = DeterministicGuid(key);

            // Match on the deterministic GUID first, then the alias, so an Umbraco Deploy
            // artifact for the same item is never duplicated whatever the order of operations
            var existingItem = await _dictionaryItemService.GetAsync(itemId)
                               ?? await _dictionaryItemService.GetAsync(key);
            if (existingItem != null)
            {
                _logger.Log(SeedLogLevel, "Key already exists: {DictionaryKey}", key);
                return existingItem.Key;
            }

            var dictionaryItem = new DictionaryItem(parentKey, key)
            {
                Key = itemId,
                Translations = await BuildTranslationsAsync(value)
            };

            var attempt = await _dictionaryItemService.CreateAsync(dictionaryItem, Constants.Security.SuperUserKey);
            if (attempt.Success == false)
            {
                _logger.LogWarning("Could not create translation key {DictionaryKey}: {Status}", key, attempt.Status);
                return null;
            }

            _logger.Log(SeedLogLevel, "Created translation key: {DictionaryKey}", key);
            return attempt.Result?.Key;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating key {DictionaryKey}", key);
            return null;
        }
    }

    /// <summary>
    /// The seeded wording is English, so it is only assigned to the default language and left
    /// for editors to fill in for the others
    /// </summary>
    private async Task<List<IDictionaryTranslation>> BuildTranslationsAsync(string value)
    {
        var defaultIsoCode = await _languageService.GetDefaultIsoCodeAsync();
        var language = await _languageService.GetAsync(defaultIsoCode);

        return language is null
            ? new List<IDictionaryTranslation>()
            : new List<IDictionaryTranslation> { new DictionaryTranslation(language, value) };
    }

    // Stable GUID derived from the alias so every environment seeds the same identifier
    private static Guid DeterministicGuid(string key)
    {
        var hash = MD5.HashData(Encoding.UTF8.GetBytes(Translations.NAMESPACE + "|" + key));
        return new Guid(hash);
    }
}
